### ISSUE TITLE
Export to excel is not working in docker image

### ISSUE THREAD

**Issue by mkabab** [mvisonneau/docker-generatedata#8]
Export to Excel & CSV not working in docker image
it's getting error 500

**Comment by mvisonneau** [comment]
indeed, looks like this is the error:

```
PHP message: PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /opt/generatedata/plugins/exportTypes/Excel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:210
Stack trace:
#0 /opt/generatedata/plugins/exportTypes/Excel/Excel.class.php(59): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('./cache/c2d408c...')
#1 /opt/generatedata/resources/classes/DataGenerator.class.php(52): Excel->generate(Object(DataGenerator))
#2 /opt/generatedata/generate.php(7): DataGenerator->generate()
#3 {main}
```

**Comment by mvisonneau** [comment]
I believe this might be related: https://github.com/benkeen/generatedata/issues/411, I will have a look 👀

**Comment by mvisonneau** [comment]
ok I managed to test it, it works now following 1e89579adbbe5018ae8c6e2e9e0658ec7233bca2 thanks for raising the issue @mkabab 🙇

**Comment by mkabab** [comment]
it's working now, thank you too @mvisonneau
